// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int64            `json:"id"`
	CustomerID int64            `json:"customer_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type OrderItem struct {
	ID         int64 `json:"id"`
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	PriceInUsd int32 `json:"price_in_usd"`
}

type Product struct {
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	PriceInUsd int32            `json:"price_in_usd"`
	Quantity   int32            `json:"quantity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
