// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID         int64            `json:"id"`
	Name       string           `json:"name"`
	PriceInUsd int32            `json:"price_in_usd"`
	Quantity   int32            `json:"quantity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}
